"""empty message

Revision ID: 267614ffefca
Revises: 
Create Date: 2024-02-15 13:54:00.336385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267614ffefca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunked_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dzchunksize', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('chunkpath', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('file_upload_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'file_upload', ['file_upload_id'], ['id'])
        batch_op.drop_column('filepath')
        batch_op.drop_column('submit_record_id')
        batch_op.drop_column('filename')

    with op.batch_alter_table('file_upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_chunks', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('chunks_received', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('upload_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_upload', schema=None) as batch_op:
        batch_op.drop_column('upload_completed')
        batch_op.drop_column('chunks_received')
        batch_op.drop_column('total_chunks')

    with op.batch_alter_table('chunked_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('submit_record_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('filepath', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'submit_record', ['submit_record_id'], ['id'])
        batch_op.drop_column('file_upload_id')
        batch_op.drop_column('chunkpath')
        batch_op.drop_column('dzchunksize')

    # ### end Alembic commands ###
